# Site settings
title: "Mason Hack Club"
currentyear: 2018
description: >
  Mason Hack Club is a computer programming club at William Mason High School
  in Mason, Ohio, and is a chapter of the international Hack Club organization.
#baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://masonhackclub.com" # the base hostname & protocol for your site
# url: "https://masonhackclub.tech" # the base hostname & protocol for your site
twitter: masonhackclub
github:  mason-hack-club
email: masonhackclub@gmail.com
linkedin: "11236662"
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - "jekyll-sitemap"
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-archives"
  - "jekyll-paginate"
