# Site settings
title: "Mason Hack Club"
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://masonhackclub.tech" # the base hostname & protocol for your site
# url: "https://masonhackclub.tech" # the base hostname & protocol for your site
twitter: masonhackclub
github:  mason-hack-club
email: masonhackclub@gmail.com
linkedin: "11236662"
markdown: kramdown
permalink: /:categories/:title/
